### ISSUE TITLE
Plugin error in Logstash 8.15

### ISSUE THREAD

**Issue by kpi-nourman** [cameronkerrnz/logstash-filter-mmdb#1]
Hi @cameronkerrnz 
I got error since upgrade logstash from 7.17 to 8.15, the plugin not working anymore.
I dont now to resolve this issue, can i get help? thank you

In the logs, I got fatal error:
```
[2024-10-24T17:02:08,744][FATAL][org.logstash.Logstash    ] uncaught error (in thread [es-enrichment]>worker6)
java.lang.NoSuchMethodError: 'com.fasterxml.jackson.databind.JsonNode com.maxmind.db.Reader.get(java.net.InetAddress)'
        at org.logstashplugins.MMDB.filter(MMDB.java:157) ~[logstash-filter-mmdb-1.0.1.jar:?]
        at org.logstash.config.ir.compiler.JavaFilterDelegatorExt.doMultiFilter(JavaFilterDelegatorExt.java:81) ~[logstash-core.jar:?]
        at org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.lambda$multiFilter$0(AbstractFilterDelegatorExt.java:133) ~[logstash-core.jar:?]
        at org.logstash.instrument.metrics.timer.ConcurrentLiveTimerMetric.time(ConcurrentLiveTimerMetric.java:47) ~[logstash-core.jar:?]
        at org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multiFilter(AbstractFilterDelegatorExt.java:133) ~[logstash-core.jar:?]
        at org.logstash.generated.CompiledDataset10.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset4.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset3.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset11.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset10.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset4.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset3.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset11.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset3.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset5.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset3.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset13.compute(Unknown Source) ~[?:?]
        at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:347) ~[logstash-core.jar:?]
        at org.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.compute(CompiledPipeline.java:341) ~[logstash-core.jar:?]
        at org.logstash.execution.ObservedExecution.lambda$compute$0(ObservedExecution.java:17) ~[logstash-core.jar:?]
        at org.logstash.execution.WorkerObserver.lambda$observeExecutionComputation$0(WorkerObserver.java:39) ~[logstash-core.jar:?]
        at org.logstash.instrument.metrics.timer.ConcurrentLiveTimerMetric.time(ConcurrentLiveTimerMetric.java:47) ~[logstash-core.jar:?]
        at org.logstash.execution.WorkerObserver.lambda$executeWithTimers$1(WorkerObserver.java:50) ~[logstash-core.jar:?]
        at org.logstash.instrument.metrics.timer.ConcurrentLiveTimerMetric.time(ConcurrentLiveTimerMetric.java:47) ~[logstash-core.jar:?]
        at org.logstash.execution.WorkerObserver.executeWithTimers(WorkerObserver.java:50) ~[logstash-core.jar:?]
        at org.logstash.execution.WorkerObserver.observeExecutionComputation(WorkerObserver.java:38) ~[logstash-core.jar:?]
        at org.logstash.execution.ObservedExecution.compute(ObservedExecution.java:17) ~[logstash-core.jar:?]
        at org.logstash.execution.WorkerLoop.abortableCompute(WorkerLoop.java:113) ~[logstash-core.jar:?]
        at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:86) ~[logstash-core.jar:?]
        at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$5(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:304) ~[?:?]
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:141) ~[jruby.jar:?]
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:64) ~[jruby.jar:?]
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58) ~[jruby.jar:?]
        at org.jruby.runtime.Block.call(Block.java:144) ~[jruby.jar:?]
        at org.jruby.RubyProc.call(RubyProc.java:354) ~[jruby.jar:?]
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:111) ~[jruby.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by cameronkerrnz** [comment]
Hi, I haven’t updated the project to work with Logstash 8.x yet. I made a
start on it last night and now I’m trying to solve some Ruby (bundler)
issues.

I’ll let you know how I get on.

This particular error will be because the version of Jackson has changed
between Logstash 7 and 8… at least that’s my assumption from what I’ve seen.

**Comment by kpi-nourman** [comment]
> Hi, I haven’t updated the project to work with Logstash 8.x yet. I made a start on it last night and now I’m trying to solve some Ruby (bundler) issues. I’ll let you know how I get on. This particular error will be because the version of Jackson has changed between Logstash 7 and 8… at least that’s my assumption from what I’ve seen.

Hi @cameronkerrnz, thank you for helping me, I will wait for the good news

**Comment by cameronkerrnz** [comment]
ARCHIVED

Sorry; I am not in a position to maintain this as frequently as I would have liked, and my logstash work required a lot of updating for Logstash 8 than I had time for, so I've made the decision to archive this project. It was last known to work with Logstash 7.

I think the idea of this plugin still holds a lot of usefulness, so I'd love it someone could fork it and provide the necessary updates. You'll need to be quite confident in Gradle, Java, Ruby, JRuby.
